package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/yadav-shubh/base-middleware/graph/generated"
	"github.com/yadav-shubh/base-middleware/graph/model"
	"github.com/yadav-shubh/base-middleware/modules"
)

// CreateAppUser is the resolver for the createAppUser field.
func (r *mutationResolver) CreateAppUser(ctx context.Context, input model.AppUserInput) (*model.AppUser, error) {
	return modules.CreateAppUser(input)
}

// UpdateAppUser is the resolver for the updateAppUser field.
func (r *mutationResolver) UpdateAppUser(ctx context.Context, input model.AppUserUpdateInput) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: UpdateAppUser - updateAppUser"))
}

// DeleteAppUser is the resolver for the deleteAppUser field.
func (r *mutationResolver) DeleteAppUser(ctx context.Context, id string) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: DeleteAppUser - deleteAppUser"))
}

// GetAppUser is the resolver for the getAppUser field.
func (r *queryResolver) GetAppUser(ctx context.Context, id string) (*model.AppUser, error) {
	return modules.GetAppUser(id)
}

// GetAppUsers is the resolver for the getAppUsers field.
func (r *queryResolver) GetAppUsers(ctx context.Context, role *string, page *int, size *int) ([]*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUsers - getAppUsers"))
}

// GetAppUserByMobile is the resolver for the getAppUserByMobile field.
func (r *queryResolver) GetAppUserByMobile(ctx context.Context, mobile string) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUserByMobile - getAppUserByMobile"))
}

// GetAppUserByUsername is the resolver for the getAppUserByUsername field.
func (r *queryResolver) GetAppUserByUsername(ctx context.Context, username string) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUserByUsername - getAppUserByUsername"))
}

// GetAppUserByPreferredUsername is the resolver for the getAppUserByPreferredUsername field.
func (r *queryResolver) GetAppUserByPreferredUsername(ctx context.Context, preferredUsername string) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUserByPreferredUsername - getAppUserByPreferredUsername"))
}

// GetAppUserByIsActive is the resolver for the getAppUserByIsActive field.
func (r *queryResolver) GetAppUserByIsActive(ctx context.Context, isActive bool) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUserByIsActive - getAppUserByIsActive"))
}

// GetAppUserByIsDeleted is the resolver for the getAppUserByIsDeleted field.
func (r *queryResolver) GetAppUserByIsDeleted(ctx context.Context, isDeleted bool) (*model.AppUser, error) {
	panic(fmt.Errorf("not implemented: GetAppUserByIsDeleted - getAppUserByIsDeleted"))
}

// AppUserCreated is the resolver for the appUserCreated field.
func (r *subscriptionResolver) AppUserCreated(ctx context.Context) (<-chan *model.AppUser, error) {
	panic(fmt.Errorf("not implemented: AppUserCreated - appUserCreated"))
}

// AppUserUpdated is the resolver for the appUserUpdated field.
func (r *subscriptionResolver) AppUserUpdated(ctx context.Context) (<-chan *model.AppUser, error) {
	panic(fmt.Errorf("not implemented: AppUserUpdated - appUserUpdated"))
}

// AppUserDeleted is the resolver for the appUserDeleted field.
func (r *subscriptionResolver) AppUserDeleted(ctx context.Context) (<-chan *model.AppUser, error) {
	panic(fmt.Errorf("not implemented: AppUserDeleted - appUserDeleted"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
