package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"

	"github.com/yadav-shubh/base-middleware/graph/model"
)

// Authenticate is the resolver for the authenticate field.
func (r *mutationResolver) Authenticate(ctx context.Context, input model.AuthCodeInput) (*model.AuthCodeResponse, error) {
	panic(fmt.Errorf("not implemented: Authenticate - authenticate"))
}

// AuthInfo is the resolver for the authInfo field.
func (r *queryResolver) AuthInfo(ctx context.Context) (*model.AuthInfoResponse, error) {
	panic(fmt.Errorf("not implemented: AuthInfo - authInfo"))
}
