package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"github.com/yadav-shubh/base-middleware/modules"

	"github.com/yadav-shubh/base-middleware/graph/model"
)

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.HealthResponse, error) {
	return modules.CheckHealth(ctx), nil
}
